### ISSUE TITLE
Initial publish

### ISSUE THREAD

**Issue by ZitRos** [JS-DevTools/npm-publish#11]
Hello! Thanks for the great action.

I noticed it always fails saying

```
##[error]Error: Unable to determine the current version of @pkg/NAME on NPM. 
```

...when you do a first publish of the package (when you're just starting a repository). You need to manually push the first version, and then it will work.

Is it intended or can be fixed? I guess we can add an error handler [here](https://github.com/JS-DevTools/npm-publish/blob/5a905d14c6937160fd0bda31111bacb56c24c400/src/npm-publish.ts#L16).

Thank you.

**Comment by JamesMessinger** [comment]
Good catch.  I never thought about that because in my workflow the initial publish is usually done manually, not by CI/CD.  But it makes total sense that this package should support that use case.

I'll leave this issue open and mark it as a bug to be fixed.  I may not have the time to fix it for a while, but you're welcome to submit a PR if you have the time.

**Comment by ZitRos** [comment]
Here we go!

**Comment by ZitRos** [comment]
Ping @JamesMessinger there seems to be 2 PRs already to fix it, please review 😁

**Comment by varunsridharan** [comment]
@JamesMessinger great action. and i really need this feature. and waiting for your review on (#12 #13 ) pull request.

**Comment by JamesMessinger** [comment]
Thank you @ZitRos and @ShadyNagy for submitting PRs for this issue!  I merged @ZitRos's PR as it was more in-line with what I envisioned, but I appreciate both of you contributing!

**Comment by ZitRos** [comment]
Thanks for a great action! We use it a lot 😌

**Comment by ShadyNagy** [comment]
Thank you so much 👍
